### ISSUE TITLE
Privacy manifest missing in CocoaPods integration

### ISSUE THREAD

**Issue by dmazzoni** [criteo/ios-publisher-sdk#325]
The privacy manifest file has been introduced, but as it is not being referenced in the SDK's Podspec it will not be packaged with apps that integrate the SDK with CocoaPods.

In order for the SDK's privacy manifest file to be correctly integrated, the Podspec should define a resource bundle that includes it as follows:

```
spec.resource_bundles = {'CriteoPublisherSDK' => ['CriteoPublisherSDK/Sources/PrivacyInfo.xcprivacy']}
```

**Comment by dpgmedia-bsellar** [comment]
The date for the privacy manifest implementation is in 6 days is this is still not fixed ...

**Comment by leonardlabat** [comment]
Hello

We've just updated our pod, sorry for the delay.

Please let us know if you still encounter an issue.

Thanks

**Comment by dpgmedia-bsellar** [comment]
Hello,

I did a quick check. The release is indeed adding the manifest for cocoa pods installation. 
The CriteoPublisherSDK which contains the privacy manifest is part of my app binary.

￼

But the privacy manifest is still missing from the binary file.
https://github.com/criteo/ios-publisher-sdk/releases/download/6.1.0/CriteoPublisherSdk.Release.zip

Since we are also supporting Swift Package Manager. The only solution we had was to use a binary target targeting the file above.
See my solution posted a year ago here <https://github.com/criteo/ios-publisher-sdk/issues/94#issuecomment-1494368102>

When inspecting my app binary, I can see for example that the xcframework from Google contains the privacy manifest but not the criteo xcframework.
And since, it’s not using cocoa pods. The CriteoPublisherSDK bundle is not generated.

￼

Would it be possible to add the privacy manifest to your xcframework also ?
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk#4336762


Best regards,

Brodie Sellar
iOS Dev Advertising Front Office

￼


Medialaan 1
1800 Vilvoorde
M +32 (0)474 85 04 66
***@***.*** ***@***.***>
dpgmedia.be <https://dpgmedia.be/>
